### ISSUE TITLE
Add more ideas from previous CWs

### ISSUE THREAD

**Issue by robintw** [robintw/CW-ideas#4]
- [x] CW21 Hack day ideas
 - [x] CW21 Collaborative ideas
 - [ ] CW20 Hack day ideas
 - [x] CW20 Collborative day ideas
 - [x] CW19 Hack day ideas
 - [x] CW19 Collaborative day ideas
 - [x] CW18 Hack ideas
 - [ ] CW18 Collaborative ideas

**Comment by marioa** [comment]
CW19 Collaborative (and hack?) ideas:
- [x] A "Cite this" button for GitHub   Hackday Pitch   Stephan Druskat
- [x] Terminal History Sharing  Hackday Pitch   Jason Gates
- [x] Automating Screenshots for Documentation  Hackday Pitch   Colin Sauze
- [x] GitHub annotator/failure map      Hackday Pitch   Ilektra Christidi
- [x] Software reporting guidelines     Hackday Pitch   Alexander Konovalov
- [x] Creating a Lessons Roadmap and Proficiency Framework for Software and Data Training       Hackday Pitch   Neil Chue Hong
- [x] Slack overflow: getting permanent docs from instant messaging     Hackday Pitch   ben krikler
- [x] R2D?.. (Ready to Deposit?)        Hackday Pitch   Patrick McCann
- [x] Improving The Turing Way  Hackday Pitch   Kirstie Whitaker
- [x] Netflix of libraries      Hackday Pitch   ben Krikler
- [x] Code-literate peer-review for everyone    Hackday Pitch   Alessandro Felder
- [x] Maintainable Tutorials Made Quickly       Hackday Pitch   Adam Jackson
- [x] Is your online training material accessible?      Hackday Pitch   David Perez-Suarez
- [x] Checklists for open reproducible research Hackday Pitch   Anna Krystalli
- [x] Hover Eels        Hackday Pitch   Niall Beard
- [x] Col-Laboratory    Hackday Pitch   Niall Beard
- [x] DUQI (Documentation Utility & Quality Interrogator)       Hackday Pitch   Rebecca J Arnold
- [x] CarpenTREE
- [x] Reproducibility and Collaboration Challenges in interactive / exploratory research (*)
- [x] RSE Careers (*)
- [x] Infrastructure to support following up after a workshop / training session (*)
- [x] Best Practice Checklist (*)
- [x] Identify new roles within Academia (*) 
- [x] The Research Data Sandbox
- [x] What is my contribution? (*)
- [x] DUQI (Document Utility and Quality Interrogator) - proposal
- [x] How to map out software and data skills lessons like Duolingo - proposal
- [x] How do you motivate researchers to adopt better software practices?
- [x] Interoperability & Continuous Integration
- [x] Libflix (*)
- [x] The Docutor button

* Title not provided so created.

**Comment by marioa** [comment]
The above have not been properly designated - some are hack ideas while others are collaborative ideas.

**Comment by marioa** [comment]
CW18 Hack-ideas:
- [x] Aligning the Citation File Format and CodeMeta
- [x] Automated Network Map construction
- [x] Carpentries platform to support translations
- [x] Choose-a-Visualisation
- [x] Code is Science Manifesto 
- [x] Geospatial metadata sharing
- [x] Keeping up with the Joneses: Providing evidence for software and data citations in published papers
- [x] Productivity Approximator

**Comment by marioa** [comment]
2018 collaborative ideas:
- [x] Guidelines for research library users and providers
- [x] ASAP - Automated Software-Assisted Provisioning
- [x] SCAT (STEM Career Advising Tool)

**Comment by marioa** [comment]
Issue transferred to https://github.com/softwaresaved/CW-ideas/issues/6
